
spring.cloud.gcp.project-id: cloudsloutions
spring.cloud.gcp.credentials.location: /cloudsloutions-fd422e010b14.json

server:
  port: 80
  address: 0.0.0.0


onedj.gcp.datastore:


#spring.cloud.gcp.project-id: "cloudsloutions"
#spring.cloud.gcp.credentials.location: "/odj-starter-springboot-datastore-minimal--master/auth/cloudsloutions-fd422e010b14.json"
#
#
#server:
#  port: 8080
#  address: "localhost"


#onedj.gcp.datastore:

